app.repository.type=database

app.db.driver=org.h2.Driver
app.db.url=jdbc:h2:./data/quantitydb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
app.db.username=sa
app.db.password=

app.db.test.url=jdbc:h2:mem:quantitydb_test;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false

app.db.pool.initialSize=2
app.db.pool.maxSize=8
app.db.pool.timeoutMillis=10000

app.db.schema.path=db/schema.sql

logging.level.root=INFO
logging.level.com.app.quantitymeasurement=DEBUG
